export enum CarbonIntensityResultType {
    MIN_FORECAST = 'MINIMUM_CARBON_INTENSITY_FORECAST',
    MAX_FORECAST = 'MAXIMUM_CARBON_INTENSITY_FORECAST',
    MIN_MEASURED = 'MINIMUM_CARBON_INTENSITY_MEASURED',
    MAX_MEASURED = 'MAXIMUM_CARBON_INTENSITY_MEASURED',
    AVG_MEASURED = 'AVG_CARBON_INTENSITY_MEASURED',
    AVG_FORECAST = 'AVG_CARBON_INTENSITY_FORECAST'
}
