export enum CarbonIntensityResultType {
    MINIMUM_CARBON_INTENSITY_FORECAST = 'MINIMUM CARBON INTENSITY FORECAST',
    MAXIMUM_CARBON_INTENSITY_FORECAST = 'MAXIMUM CARBON INTENSITY FORECAST',
    MINIMUM_CARBON_INTENSITY_MEASURED = 'MINIMUM CARBON INTENSITY MEASURED',
    MAXIMUM_CARBON_INTENSITY_MEASURED = 'MAXIMUM CARBON INTENSITY MEASURED',
    AVG_CARBON_INTENSITY_MEASURED = 'AVERAGE CARBON INTENSITY MEASURED',
    AVG_CARBON_INTENSITY_FORECAST = 'AVERAGE CARBON INTENSITY FORECAST'
}

export const isExtremeType = (type: CarbonIntensityResultType): boolean => {
    return [CarbonIntensityResultType.MINIMUM_CARBON_INTENSITY_FORECAST,
    CarbonIntensityResultType.MAXIMUM_CARBON_INTENSITY_FORECAST,
    CarbonIntensityResultType.MINIMUM_CARBON_INTENSITY_MEASURED,
    CarbonIntensityResultType.MAXIMUM_CARBON_INTENSITY_MEASURED].includes(type);
};

